name: calorie_counter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  intl: ^0.19.0
  material_symbols_icons: ^4.2785.1
  mobile_scanner: ^6.0.2
  openfoodfacts: ^3.15.0
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.20.3
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
